<?php echo $this->doctype(); ?>

<html lang="pt-BR">
    <head>
        <meta charset="utf-8">

        <!-- Styles -->
        <?php
        echo $this
                ->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ;
        ?>
    </head>
    <body>
        <?php
        if (isset($messages[0])):
            $class = key((array) $messages[0]);
            $message = current((array) $messages[0]);
            ?>
            <div class="alert alert-<?php echo $class ?>">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <?php echo $message ?>
            </div>
        <?php endif; ?>

        <div id="cabesalho">
            <img src="<?php echo $this->basePath('img/logo.png') ?>"/>
            <h1  class="h1">Academia Movimento</h1><h1 class="h2">Joaosinho 
                <a class="but" href="<?php echo $this->url('home', array('action' => 'index')) ?>" title="Novo">Sair</a></h1>
        </div>
        <div class="corpo">
             <?php echo $this->content; ?>
        </div>

        <!-- Scripts -->
        <?php
        echo $this
                ->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ;

        echo $this->inlineScript();
        ?>
    </body>
</html>